#!/usr/bin/env bash
set -euo pipefail

# Dual-node FTP-1 launch. Required env:
#   FTP1_JOB_NAME, FTP1_NODE_RANK, FTP1_MASTER_ADDR, FTP1_MASTER_PORT
#   FTP1_DATASET_CONFIG, FTP1_VALIDATION_REPORT, FTP1_EXPECTED_SOURCE_ROOT
#   FTP1_REPO_ID, FTP1_EXP_NAME
WORKSPACE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${WORKSPACE_ROOT}"
ulimit -n 1048576 || true

export FTP1_STAGE="${FTP1_STAGE:-train}"
export FTP1_NORM_NUM_WORKERS="${FTP1_NORM_NUM_WORKERS:-4}"
export PYTHONUNBUFFERED=1
export FTP1_NNODES="${FTP1_NNODES:-2}"
export FTP1_LOCAL_BATCH_SIZE="${FTP1_LOCAL_BATCH_SIZE:-8}"
export FTP1_NUM_TRAIN_STEPS="${FTP1_NUM_TRAIN_STEPS:-80000}"
export FTP1_SAVE_INTERVAL="${FTP1_SAVE_INTERVAL:-10000}"
export FTP1_VAL_INTERVAL="${FTP1_VAL_INTERVAL:-10000}"
export FTP1_WANDB_ENABLED=1
export FTP1_WANDB_MODE=online
export FTP1_WANDB_PROJECT="${FTP1_WANDB_PROJECT:-xpolicylab-0910-real}"
export FTP1_WANDB_ENTITY="${FTP1_WANDB_ENTITY:-peichengxiang773-hkust}"
export NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-0}"
export NCCL_SOCKET_IFNAME="${NCCL_SOCKET_IFNAME:-eth0}"
export GLOO_SOCKET_IFNAME="${GLOO_SOCKET_IFNAME:-eth0}"
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"

exec bash XPolicyLab/policy/FTP_1/train.sh \
  Spark0_real_bench_v5 Moxian tianji_marvin_wuji ee 42 0,1,2,3,4,5,6,7
